import type {
  Customer,
  KitchenTicket,
  Order,
  Product,
  RestaurantTable,
  RevenuePoint,
  StaffMember,
} from "./types";

const img = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?w=400&q=80&auto=format&fit=crop`;

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Artisan Latte",
    sku: "SKU-1001",
    description: "12oz • Double shot",
    price: 4.5,
    cost: 1.2,
    category: "Coffee & Tea",
    imageUrl: img("1561882468-9110e03e0f78"),
    stock: 120,
    reorderPoint: 30,
    isActive: true,
  },
  {
    id: "p2",
    name: "Double Espresso",
    sku: "SKU-1002",
    description: "Standard 2oz",
    price: 3.0,
    cost: 0.8,
    category: "Coffee & Tea",
    imageUrl: img("1510591509098-f4fdc6d0ff04"),
    stock: 200,
    reorderPoint: 40,
    isActive: true,
  },
  {
    id: "p3",
    name: "Butter Croissant",
    sku: "SKU-1003",
    description: "Fresh baked daily",
    price: 3.75,
    cost: 1.1,
    category: "Pastries",
    imageUrl: img("1555507036-ab1f4038808a"),
    stock: 45,
    reorderPoint: 20,
    isActive: true,
  },
  {
    id: "p4",
    name: "Green Revive Juice",
    sku: "SKU-1004",
    description: "16oz • Cold pressed",
    price: 6.5,
    cost: 2.3,
    category: "Beverages",
    imageUrl: img("1610970881699-44a5587cabec"),
    stock: 32,
    reorderPoint: 15,
    isActive: true,
  },
  {
    id: "p5",
    name: "Avocado Toast",
    sku: "SKU-1005",
    description: "Sourdough • Organic",
    price: 12.0,
    cost: 3.5,
    category: "Cold Sandwiches",
    imageUrl: img("1588137378633-dea1336ce1e2"),
    stock: 18,
    reorderPoint: 10,
    isActive: true,
  },
  {
    id: "p6",
    name: "Ancient Grain Pretzels",
    sku: "SKU-1029",
    description: "Organic snacks",
    price: 4.25,
    cost: 1.0,
    category: "Snacks",
    imageUrl: img("1559656914-a30970c1affd"),
    stock: 142,
    reorderPoint: 60,
    isActive: true,
  },
  {
    id: "p7",
    name: "Arctic Spring Water",
    sku: "SKU-4402",
    description: "Beverages",
    price: 2.5,
    cost: 0.4,
    category: "Beverages",
    imageUrl: img("1548839140-29a749e1cf4d"),
    stock: 12,
    reorderPoint: 30,
    isActive: true,
  },
  {
    id: "p8",
    name: "Ethiopian Arabica",
    sku: "SKU-2911",
    description: "Whole bean • 12oz bag",
    price: 18.0,
    cost: 7.2,
    category: "Coffee & Tea",
    imageUrl: img("1559496417-e7f25cb247f3"),
    stock: 54,
    reorderPoint: 25,
    isActive: true,
  },
  {
    id: "p9",
    name: "Volt Max Energy",
    sku: "SKU-8821",
    description: "Beverages",
    price: 3.5,
    cost: 0.9,
    category: "Beverages",
    imageUrl: img("1622543925917-9bc9f4fff084"),
    stock: 0,
    reorderPoint: 50,
    isActive: true,
  },
  {
    id: "p10",
    name: "Matcha Latte",
    sku: "SKU-1010",
    description: "Ceremonial grade",
    price: 5.25,
    cost: 1.6,
    category: "Coffee & Tea",
    imageUrl: img("1536256263959-770b48d82b0a"),
    stock: 88,
    reorderPoint: 30,
    isActive: true,
  },
];

const todayIso = (offsetMinutes = 0) =>
  new Date(Date.now() - offsetMinutes * 60_000).toISOString();

export const mockOrders: Order[] = [
  {
    id: "o1",
    number: "#10241",
    createdAt: todayIso(8),
    customerName: "Walk-in",
    items: [
      { productId: "p1", name: "Artisan Latte", quantity: 2, unitPrice: 4.5 },
      { productId: "p3", name: "Butter Croissant", quantity: 1, unitPrice: 3.75 },
    ],
    subtotal: 12.75,
    tax: 1.08,
    total: 13.83,
    status: "preparing",
    payment: "card",
    tableId: "t2",
  },
  {
    id: "o2",
    number: "#10240",
    createdAt: todayIso(22),
    customerName: "Jordan Doe",
    items: [{ productId: "p5", name: "Avocado Toast", quantity: 1, unitPrice: 12 }],
    subtotal: 12,
    tax: 1.02,
    total: 13.02,
    status: "ready",
    payment: "wallet",
  },
  {
    id: "o3",
    number: "#10239",
    createdAt: todayIso(45),
    customerName: "Sarah Chen",
    items: [
      { productId: "p4", name: "Green Revive Juice", quantity: 2, unitPrice: 6.5 },
      { productId: "p10", name: "Matcha Latte", quantity: 1, unitPrice: 5.25 },
    ],
    subtotal: 18.25,
    tax: 1.55,
    total: 19.8,
    status: "completed",
    payment: "card",
  },
  {
    id: "o4",
    number: "#10238",
    createdAt: todayIso(60),
    customerName: "Marcus Lee",
    items: [{ productId: "p8", name: "Ethiopian Arabica", quantity: 1, unitPrice: 18 }],
    subtotal: 18,
    tax: 1.53,
    total: 19.53,
    status: "completed",
    payment: "cash",
  },
  {
    id: "o5",
    number: "#10237",
    createdAt: todayIso(95),
    customerName: "Walk-in",
    items: [{ productId: "p2", name: "Double Espresso", quantity: 3, unitPrice: 3 }],
    subtotal: 9,
    tax: 0.77,
    total: 9.77,
    status: "pending",
    payment: "card",
    tableId: "t5",
  },
  {
    id: "o6",
    number: "#10236",
    createdAt: todayIso(140),
    customerName: "Riley Park",
    items: [
      { productId: "p6", name: "Ancient Grain Pretzels", quantity: 2, unitPrice: 4.25 },
      { productId: "p7", name: "Arctic Spring Water", quantity: 2, unitPrice: 2.5 },
    ],
    subtotal: 13.5,
    tax: 1.15,
    total: 14.65,
    status: "cancelled",
    payment: "card",
  },
];

export const mockTables: RestaurantTable[] = [
  { id: "t1", label: "T1", seats: 2, status: "available" },
  { id: "t2", label: "T2", seats: 4, status: "occupied", orderId: "o1" },
  { id: "t3", label: "T3", seats: 4, status: "reserved" },
  { id: "t4", label: "T4", seats: 6, status: "cleaning" },
  { id: "t5", label: "T5", seats: 2, status: "occupied", orderId: "o5" },
  { id: "t6", label: "T6", seats: 8, status: "available" },
  { id: "t7", label: "T7", seats: 2, status: "available" },
  { id: "t8", label: "T8", seats: 4, status: "occupied" },
  { id: "t9", label: "T9", seats: 4, status: "available" },
  { id: "t10", label: "T10", seats: 6, status: "reserved" },
  { id: "t11", label: "T11", seats: 2, status: "available" },
  { id: "t12", label: "T12", seats: 4, status: "available" },
];

export const mockTickets: KitchenTicket[] = [
  {
    id: "k1",
    orderNumber: "#10241",
    tableLabel: "T2",
    items: [
      { name: "Artisan Latte", quantity: 2 },
      { name: "Butter Croissant", quantity: 1, note: "Warmed" },
    ],
    status: "in_progress",
    createdAt: todayIso(6),
  },
  {
    id: "k2",
    orderNumber: "#10242",
    tableLabel: "T5",
    items: [
      { name: "Double Espresso", quantity: 3 },
      { name: "Avocado Toast", quantity: 1, note: "No chili" },
    ],
    status: "new",
    createdAt: todayIso(2),
  },
  {
    id: "k3",
    orderNumber: "#10240",
    items: [{ name: "Avocado Toast", quantity: 1 }],
    status: "ready",
    createdAt: todayIso(14),
  },
  {
    id: "k4",
    orderNumber: "#10239",
    tableLabel: "T8",
    items: [
      { name: "Green Revive Juice", quantity: 2 },
      { name: "Matcha Latte", quantity: 1 },
    ],
    status: "new",
    createdAt: todayIso(1),
  },
];

export const mockCustomers: Customer[] = [
  { id: "c1", name: "Jordan Doe", email: "jordan@example.com", phone: "+1 415 555 0102", totalSpent: 482.5, orderCount: 27, loyaltyPoints: 480, joinedAt: "2024-03-12" },
  { id: "c2", name: "Sarah Chen", email: "sarah@example.com", phone: "+1 415 555 0144", totalSpent: 1240, orderCount: 64, loyaltyPoints: 1240, joinedAt: "2023-11-04" },
  { id: "c3", name: "Marcus Lee", email: "marcus@example.com", phone: "+1 415 555 0188", totalSpent: 92.4, orderCount: 6, loyaltyPoints: 90, joinedAt: "2025-01-09" },
  { id: "c4", name: "Riley Park", email: "riley@example.com", totalSpent: 318, orderCount: 19, loyaltyPoints: 318, joinedAt: "2024-07-21" },
  { id: "c5", name: "Avery Stone", email: "avery@example.com", totalSpent: 56.2, orderCount: 4, loyaltyPoints: 56, joinedAt: "2025-04-02" },
  { id: "c6", name: "Kai Nakamura", email: "kai@example.com", totalSpent: 2104.9, orderCount: 112, loyaltyPoints: 2100, joinedAt: "2023-02-18" },
];

export const mockStaff: StaffMember[] = [
  { id: "s1", name: "Alex Rivera", email: "alex@inventorypro.com", role: "admin", status: "active", hireDate: "2022-06-01" },
  { id: "s2", name: "Jordan Doe", email: "jordan@inventorypro.com", role: "manager", status: "active", hireDate: "2023-01-15" },
  { id: "s3", name: "Sarah Chen", email: "sarah@inventorypro.com", role: "cashier", status: "active", hireDate: "2024-03-08" },
  { id: "s4", name: "Marcus Lee", email: "marcus@inventorypro.com", role: "cashier", status: "offline", hireDate: "2024-09-22" },
  { id: "s5", name: "Priya Patel", email: "priya@inventorypro.com", role: "kitchen", status: "on_break", hireDate: "2024-05-30" },
  { id: "s6", name: "Tom Becker", email: "tom@inventorypro.com", role: "server", status: "active", hireDate: "2025-02-11" },
];

export const mockRevenueWeekly: RevenuePoint[] = [
  { label: "Mon", current: 1820, previous: 1640 },
  { label: "Tue", current: 2110, previous: 1980 },
  { label: "Wed", current: 1640, previous: 1810 },
  { label: "Thu", current: 2540, previous: 2240 },
  { label: "Fri", current: 3210, previous: 2870 },
  { label: "Sat", current: 3480, previous: 3120 },
  { label: "Sun", current: 1200, previous: 1140 },
];

export const mockRevenueMonthly: RevenuePoint[] = Array.from({ length: 6 }).map((_, i) => ({
  label: `WK ${i + 1}`,
  current: 8000 + Math.round(Math.sin(i + 1) * 3000 + i * 700 + 4000),
  previous: 7400 + Math.round(Math.cos(i + 1) * 2600 + i * 500 + 3500),
}));

export const mockCategoryBreakdown = [
  { name: "Coffee & Tea", value: 42 },
  { name: "Pastries", value: 18 },
  { name: "Cold Sandwiches", value: 14 },
  { name: "Beverages", value: 16 },
  { name: "Snacks", value: 10 },
];
